version: '3.9'
services: 
    myapp:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                RBASE_VERSION: ${RBASE_VERSION}
                SHINY_PACKAGE: ${SHINY_PACKAGE}
                SHINY_LOG_LEVEL: ${SHINY_LOG_LEVEL}
        image: myapp:1.0.0
        hostname: myapp
        ports: 
            - 3838:${SHINY_LISTENING_PORT}
    